<?php

// create custom fields for post type post
add_action('acf/include_fields', 'ncmazFC__acf_add_local_field_groups');
if (!function_exists("ncmazFC__acf_add_local_field_groups")) :

    function ncmazFC__acf_add_local_field_groups()
    {
        if (!function_exists('acf_add_local_field_group')) {
            return;
        }

        acf_add_local_field_group(array(
            'key' => 'group_ncmazAudioUrl',
            'title' => 'Audio Url',
            'fields' => array(
                array(
                    'key' => 'field_615317803e567',
                    'label' => 'Audio Url (Youtube/mp4/mp3)',
                    'name' => 'audio_url',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_format',
                        'operator' => '==',
                        'value' => 'audio',
                    ),
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'post',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_graphql' => 1,
            'graphql_field_name' => 'ncmazAudioUrl',
            'map_graphql_types_from_location_rules' => 0,
            'graphql_types' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_615d31944c1a9f',
            'title' => 'Gallery Images (Max 8 images)',
            'fields' => array(
                array(
                    'key' => 'field_61531f96407eda',
                    'label' => 'image1',
                    'name' => 'image_1',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_6153199307edb',
                    'label' => 'image2',
                    'name' => 'image_2',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_615319a207edc',
                    'label' => 'image3',
                    'name' => 'image_3',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_615319a907edd',
                    'label' => 'image4',
                    'name' => 'image_4',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_615319b607ede',
                    'label' => 'image5',
                    'name' => 'image_5',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_615319be07edf',
                    'label' => 'image6',
                    'name' => 'image_6',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_615319c907ee0',
                    'label' => 'image7',
                    'name' => 'image_7',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_615319d207ee1',
                    'label' => 'image8',
                    'name' => 'image_8',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_format',
                        'operator' => '==',
                        'value' => 'gallery',
                    ),
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'post',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_graphql' => 1,
            'graphql_field_name' => 'ncmazGalleryImgs',
            'map_graphql_types_from_location_rules' => 0,
            'graphql_types' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_6153172f84fd0',
            'title' => 'Video Url',
            'fields' => array(
                array(
                    'key' => 'field_6153174a5583d',
                    'label' => 'Video URL (Youtube, Vimeo, etc.)',
                    'name' => 'video_url',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_format',
                        'operator' => '==',
                        'value' => 'video',
                    ),
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'post',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_graphql' => 1,
            'graphql_field_name' => 'ncmazVideoUrl',
            'map_graphql_types_from_location_rules' => 0,
            'graphql_types' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_61531796982ba',
            'title' => 'Ncmaz Post Meta Data',
            'fields' => array(
                array(
                    'key' => 'field_64c0f524b7f38',
                    'label' => 'Show Right Sidebar',
                    'name' => 'show_right_sidebar',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui' => 0,
                    'show_in_graphql' => 1,
                    'graphql_description' => '',
                    'graphql_field_name' => 'showRightSidebar',
                    'graphql_non_null' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                array(
                    'key' => 'field_64c0f41ec8fa6',
                    'label' => 'Template Style',
                    'name' => 'template',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => 'Applies to standard post format only',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'style1' => 'Style 1',
                        'style2' => 'Style 2',
                        'style3' => 'Style 3',
                        'style4' => 'Style 4',
                    ),
                    'default_value' => 'style1',
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 0,
                    'show_in_graphql' => 1,
                    'graphql_description' => '',
                    'graphql_field_name' => 'template',
                    'graphql_non_null' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_64c0f19a92b15',
                    'label' => 'Views Count',
                    'name' => 'views_count',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 1,
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                    'show_in_graphql' => 1,
                    'graphql_description' => '',
                    'graphql_field_name' => 'viewsCount',
                    'graphql_non_null' => 0,
                ),
                array(
                    'key' => 'field_64c0f2db155ea',
                    'label' => 'Likes Count',
                    'name' => 'likes_count',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                    'show_in_graphql' => 1,
                    'graphql_description' => '',
                    'graphql_field_name' => 'likesCount',
                    'graphql_non_null' => 0,
                ),
                array(
                    'key' => 'field_64c0f3a6e7035',
                    'label' => 'Saveds Count',
                    'name' => 'saveds_count',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '24',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                    'show_in_graphql' => 1,
                    'graphql_description' => '',
                    'graphql_field_name' => 'savedsCount',
                    'graphql_non_null' => 0,
                ),
                array(
                    'key' => 'field_64bc64098ba9d8',
                    'label' => 'Reading time in minutes',
                    'name' => 'reading_time',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '24',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => 1,
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'post',
                    ),
                ),
            ),
            'menu_order' => 1,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_graphql' => 1,
            'graphql_field_name' => 'ncPostMetaData',
            'map_graphql_types_from_location_rules' => 0,
            'graphql_types' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_6153167c42978',
            'title' => 'Ncmaz Taxonomy Meta',
            'fields' => array(
                array(
                    'key' => 'field_6153169776754',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'choices' => array(
                        'pink' => 'pink',
                        'red' => 'red',
                        'gray' => 'gray',
                        'green' => 'green',
                        'purple' => 'purple',
                        'indigo' => 'indigo',
                        'yellow' => 'yellow',
                        'blue' => 'blue',
                        'slate' => 'slate',
                        'teal' => 'teal',
                        'amber' => 'amber',
                        'emerald' => 'emerald',
                        'lime' => 'lime',
                        'rose' => 'rose',
                        'fuchsia' => 'fuchsia',
                        'cyan' => 'cyan',
                        'lightBlue' => 'lightBlue',
                        'violet' => 'violet',
                        'sky' => 'sky',
                        'orange' => 'orange',
                        'lightGreen' => 'lightGreen',
                    ),
                    'default_value' => 'green',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_615316f276755',
                    'label' => 'Featured Image',
                    'name' => 'featured_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'taxonomy',
                        'operator' => '==',
                        'value' => 'category',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_graphql' => 1,
            'graphql_field_name' => 'ncTaxonomyMeta',
            'map_graphql_types_from_location_rules' => 0,
            'graphql_types' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_6152da3dd9b84',
            'title' => 'Ncmaz User Meta',
            'fields' => array(
                array(
                    'key' => 'field_6152dc15767fb',
                    'label' => 'Featured Image',
                    'name' => 'featured_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_6153157770fcf',
                    'label' => 'Cover Image',
                    'name' => 'background_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_6152da69a6827',
                    'label' => 'Job/Career',
                    'name' => 'nc_bio',
                    'type' => 'text',
                    'instructions' => 'Job/Career of the user. Example: Web Developer, Designer, etc.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => 'Designer',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                // 
                [
                    'key' => 'field_6153153270fcb_youtube_url',
                    'label' => 'Youtube Url',
                    'name' => 'youtube_url',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_6153153270fxcb_tiktok_url',
                    'label' => 'Tiktok Url',
                    'name' => 'tiktok_url',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_b70fcd_facebook_url',
                    'label' => 'Facebook Url',
                    'name' => 'facebook_url',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_61555b70fcd_medium_url',
                    'label' => 'Medium Url',
                    'name' => 'medium_url',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_615dsb70fcd_github_url',
                    'label' => 'Github Url',
                    'name' => 'github_url',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_61ddb70fcd_vimeo_url',
                    'label' => 'Vimeo Url',
                    'name' => 'vimeo_url',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_6dd70fcc_twitter_url',
                    'label' => 'Twitter Url',
                    'name' => 'twitter_url',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_615db70fce_instagram_url',
                    'label' => 'Instagram Url',
                    'name' => 'instagram_url',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_615dfce_linkedin_url',
                    'label' => 'Linkedin Url',
                    'name' => 'linkedin_url',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_61d0fce_pinterest_url',
                    'label' => 'Pinterest Url',
                    'name' => 'pinterest_url',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_6fce_twitch_url',
                    'label' => 'Twitch Url',
                    'name' => 'twitch_url',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_6fc342dfe_website_url',
                    'label' => 'Website Url',
                    'name' => 'website_url',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_6sfe_buymeacoffe_url',
                    'label' => 'Buymeacoffe Url',
                    'name' => 'buymeacoffe_url',
                    'type' => 'text',
                    'instructions' => 'You should have an account here or something similar -  https://www.buymeacoffee.com',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                ],
                // 
                array(
                    'key' => 'field_6152da59a6826_color',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_graphql' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'user_form',
                        'operator' => '==',
                        'value' => 'edit',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_graphql' => 1,
            'graphql_field_name' => 'ncUserMeta',
            'map_graphql_types_from_location_rules' => 0,
            'graphql_types' => '',
        ));
    }

endif;

// creage custom post type for user reaction
add_action('init', function () {
    register_post_type('user-reaction-post', array(
        'labels' => array(
            'name' => 'User Reaction Posts',
            'singular_name' => 'User Reaction Post',
            'menu_name' => 'User reaction posts',
            'all_items' => 'All User reaction posts',
            'edit_item' => 'Edit User reaction post',
            'view_item' => 'View User reaction post',
            'view_items' => 'View User reaction posts',
            'add_new_item' => 'Add New User reaction post',
            'new_item' => 'New User reaction post',
            'parent_item_colon' => 'Parent User reaction post:',
            'search_items' => 'Search User reaction posts',
            'not_found' => 'No user reaction posts found',
            'not_found_in_trash' => 'No user reaction posts found in Trash',
            'archives' => 'User reaction post Archives',
            'attributes' => 'User reaction post Attributes',
            'insert_into_item' => 'Insert into user reaction post',
            'uploaded_to_this_item' => 'Uploaded to this user reaction post',
            'filter_items_list' => 'Filter user reaction posts list',
            'filter_by_date' => 'Filter user reaction posts by date',
            'items_list_navigation' => 'User reaction posts list navigation',
            'items_list' => 'User reaction posts list',
            'item_published' => 'User reaction post published.',
            'item_published_privately' => 'User reaction post published privately.',
            'item_reverted_to_draft' => 'User reaction post reverted to draft.',
            'item_scheduled' => 'User reaction post scheduled.',
            'item_updated' => 'User reaction post updated.',
            'item_link' => 'User reaction post Link',
            'item_link_description' => 'A link to a user reaction post.',
        ),
        'description' => 'Intermediate table to store information about each user\'s post retention.',
        'public' => true,
        'exclude_from_search' => true,
        'show_in_rest' => true,
        'supports' => array(
            0 => 'title',
            1 => 'author',
        ),
        'delete_with_user' => true,
        'show_in_graphql' => true,
        'graphql_single_name' => 'userReactionPost',
        'graphql_plural_name' => 'userReactionPosts',
    ));
});


//  add custom fields to menu / mega menu
add_action('acf/include_fields', function () {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_64c526cd8e979',
        'title' => 'NcmazFaust Custom Menu',
        'fields' => array(
            array(
                'key' => 'field_64c526cfe7020',
                'label' => 'Is Mega Menu',
                'name' => 'is_mega_menu',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => 'Option to display menu as mega menu. Mega menu will contain many menu columns inside and a few featured articles. Each level 1 submenu of this menu will represent a menu column, and the level 1 menus of that menu will be in that column. Up to 6 columns.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'isMegaMenu',
                'graphql_non_null' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_64c52931c8010',
                'label' => 'Posts',
                'name' => 'posts',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => 'Select posts which will be show in the right side of the mega menu (These can be the most special articles or something like that). The number of posts displayed will depend on the number of existing menu columns inside the mega menu. No menu column => Display up to 5 posts. One menu column => Display up to 4 posts.Two menu columns => Display up to 3 posts. Three or four menu columns => Display up to 2 posts. Five menu columns => Display up to 1 post. Six menu columns => Will not display any posts',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_64c526cfe7020',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'post',
                ),
                'post_status' => '',
                'taxonomy' => '',
                'return_format' => 'id',
                'multiple' => 1,
                'allow_null' => 0,
                'show_in_graphql' => 1,
                'graphql_description' => 'Select posts which will be show in the right side of the mega menu.The number of posts displayed will depend on the number of existing menu columns inside the mega menu. No menu column => Display up to 5 posts. One menu column => Display up to 4 postsTwo menu columns => Display up to 3 postsThree or four menu columns => Display up to 2 postsFive menu columns => Display up to 1 postSix menu columns => Will not display any posts',
                'graphql_field_name' => 'posts',
                'ui' => 1,
            ),
            array(
                'key' => 'field_64c99b47188cd',
                'label' => 'Number of menu columns',
                'name' => 'number_of_menu_columns',
                'aria-label' => '',
                'type' => 'range',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_64c526cfe7020',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 4,
                'min' => '',
                'max' => 8,
                'step' => '',
                'prepend' => '',
                'append' => '',
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'numberOfMenuColumns',
                'graphql_non_null' => 0,
            ),
            // array(
            //     'key' => 'field_64c99b6a188ce',
            //     'label' => 'Number of post columns',
            //     'name' => 'number_of_post_columns',
            //     'aria-label' => '',
            //     'type' => 'range',
            //     'instructions' => '',
            //     'required' => 0,
            //     'conditional_logic' => array(
            //         array(
            //             array(
            //                 'field' => 'field_64c526cfe7020',
            //                 'operator' => '==',
            //                 'value' => '1',
            //             ),
            //         ),
            //     ),
            //     'wrapper' => array(
            //         'width' => '',
            //         'class' => '',
            //         'id' => '',
            //     ),
            //     'default_value' => 2,
            //     'min' => '',
            //     'max' => 6,
            //     'step' => '',
            //     'prepend' => '',
            //     'append' => '',
            //     'show_in_graphql' => 1,
            //     'graphql_description' => '',
            //     'graphql_field_name' => 'numberOfPostColumns',
            //     'graphql_non_null' => 0,
            // ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'nav_menu_item',
                    'operator' => '==',
                    'value' => 'location/primary',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'show_in_graphql' => 1,
        'graphql_field_name' => 'ncmazfaustMenu',
        'map_graphql_types_from_location_rules' => 0,
        'graphql_types' => '',
    ));
});


// add custom fields to page
add_action('acf/include_fields', function () {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_64e81a9c26583',
        'title' => 'Ncmaz page meta',
        'fields' => array(
            array(
                'key' => 'field_64e81a9cc8f30',
                'label' => 'Is full-with page',
                'name' => 'is_full-with_page',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'If true, the page will be rendered full-width, and the title will be hidden. Same as front-page.',
                'default_value' => 0,
                'ui' => 0,
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'isFullWithPage',
                'graphql_non_null' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'show_in_graphql' => 1,
        'graphql_field_name' => 'ncPageMeta',
        'map_graphql_types_from_location_rules' => 0,
        'graphql_types' => '',
    ));
});


add_action('acf/include_fields', function () {
    if (! function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_6746dfa35a8af',
        'title' => 'User reaction fields',
        'fields' => array(
            array(
                'key' => 'field_6746dfa31c7a2',
                'label' => 'Liked posts',
                'name' => 'liked_posts',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '0',
                    'class' => 'hidden acf-hidden',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 1,
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'likedPosts',
                'graphql_non_null' => 0,
            ),
            array(
                'key' => 'field_6746e0961c7a3',
                'label' => 'Saved posts',
                'name' => 'saved_posts',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '0',
                    'class' => 'hidden acf-hidden',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 1,
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'savedPosts',
                'graphql_non_null' => 0,
            ),
            array(
                'key' => 'field_6746e0b31c7a4',
                'label' => 'Viewed posts',
                'name' => 'viewed_posts',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '0',
                    'class' => 'hidden acf-hidden',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 1,
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
                'show_in_graphql' => 1,
                'graphql_description' => '',
                'graphql_field_name' => 'viewedPosts',
                'graphql_non_null' => 0,
            ),

        ),
        'location' => array(
            array(
                array(
                    'param' => 'user_role',
                    'operator' => '==',
                    'value' => 'all',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 1,
        'show_in_graphql' => 1,
        'graphql_field_name' => 'userReactionFields',
        'map_graphql_types_from_location_rules' => 0,
        'graphql_types' => '',
    ));
});
